version: 0.0.{build}
configuration:
- Debug
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    CMAKE_GEN_TYPE: '"Visual Studio 10 2010"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    CMAKE_GEN_TYPE: '"Visual Studio 11 2012"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    CMAKE_GEN_TYPE: '"Visual Studio 12 2013"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_GEN_TYPE: '"Visual Studio 14 2015"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GEN_TYPE: '"Visual Studio 15 2017"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GEN_TYPE: '"Visual Studio 15 2017 Win64"'

install:
- ps: >-
    pip install backports.tempfile
build_script:
- ps: >-

    git submodule update --init

    if(!(Test-Path -Path build )){
      mkdir build
    }
    
    cd tests
    
    python create_large_testdata.py 
    
    cd ../

    cd build

    cmake ../ -G $env:CMAKE_GEN_TYPE -Dgtest_force_shared_crt=ON

    cmake --build . --config $env:CONFIGURATION
test_script:
- ps: ctest -C $env:CONFIGURATION --output-on-failure
